# Generated by Django 4.2.5 on 2023-09-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_card", models.BigIntegerField(unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.BigIntegerField()),
                ("password", models.CharField(max_length=9999)),
                ("balance", models.FloatField(default=0.0)),
                ("withdraw_code", models.IntegerField(null=True)),
                ("withdraw_code_expiration", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "accounts",
            },
        ),
    ]
