# Generated by Django 4.2.3 on 2023-07-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="account",
            name="id_card",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="phone",
            field=models.BigIntegerField(),
        ),
    ]
