# Generated by Django 4.2.3 on 2023-07-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_balance_alter_account_id_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="withdraw_code",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="withdraw_code_expiration",
            field=models.DateTimeField(null=True),
        ),
    ]
